# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

emfit_mapgen_group <- function(alpha, xi, D0, D1, data, options, P0, P1, H0, H1, en0, en1) {
    .Call(`_mapfit_emfit_mapgen_group`, alpha, xi, D0, D1, data, options, P0, P1, H0, H1, en0, en1)
}

emfit_gmmpp_group <- function(alpha, xi, D0, D1, data, options, P0, P1, en0, en1, G, PsiT1, PsiT2, PsiN1, PsiN2, tmpm) {
    .Call(`_mapfit_emfit_gmmpp_group`, alpha, xi, D0, D1, data, options, P0, P1, en0, en1, G, PsiT1, PsiT2, PsiN1, PsiN2, tmpm)
}

emfit_cf1_wtime <- function(alpha, rate, data, options, Q0, P0, H0) {
    .Call(`_mapfit_emfit_cf1_wtime`, alpha, rate, data, options, Q0, P0, H0)
}

emfit_cf1_group <- function(alpha, rate, data, options, Q0, P0, H0) {
    .Call(`_mapfit_emfit_cf1_group`, alpha, rate, data, options, Q0, P0, H0)
}

emfit_cf1_group_poi <- function(omega, alpha, rate, data, options, Q0, P0, H0) {
    .Call(`_mapfit_emfit_cf1_group_poi`, omega, alpha, rate, data, options, Q0, P0, H0)
}

emfit_gph_wtime <- function(alpha, Q0, xi, data, options, P0, H0) {
    .Call(`_mapfit_emfit_gph_wtime`, alpha, Q0, xi, data, options, P0, H0)
}

emfit_gph_group <- function(alpha, Q0, xi, data, options, P0, H0) {
    .Call(`_mapfit_emfit_gph_group`, alpha, Q0, xi, data, options, P0, H0)
}

emfit_gph_group_poi <- function(omega, alpha, Q0, xi, data, options, P0, H0) {
    .Call(`_mapfit_emfit_gph_group_poi`, omega, alpha, Q0, xi, data, options, P0, H0)
}

emfit_herlang_wtime <- function(alpha, shape, rate, data, options) {
    .Call(`_mapfit_emfit_herlang_wtime`, alpha, shape, rate, data, options)
}

emfit_herlang_group <- function(alpha, shape, rate, data, options) {
    .Call(`_mapfit_emfit_herlang_group`, alpha, shape, rate, data, options)
}

emfit_herlang_group_poi <- function(alpha, shape, rate, omega, data, options) {
    .Call(`_mapfit_emfit_herlang_group_poi`, alpha, shape, rate, omega, data, options)
}

phase_dist_pdf <- function(dt, maxtime, alpha, Q0, xi, eps, ufactor, P0) {
    .Call(`_mapfit_phase_dist_pdf`, dt, maxtime, alpha, Q0, xi, eps, ufactor, P0)
}

phase_dist_ccdf <- function(dt, maxtime, alpha, Q0, eps, ufactor, P0) {
    .Call(`_mapfit_phase_dist_ccdf`, dt, maxtime, alpha, Q0, eps, ufactor, P0)
}

phase_cf1_sort <- function(alpha, rate) {
    .Call(`_mapfit_phase_cf1_sort`, alpha, rate)
}

